SecureBankingApp/src/main/java/edu/asu/securebanking/beans/OTPBean.java
package edu.asu.securebanking.beans;

import java.util.Date;

/**
 * Created by Vikranth on 10/29/2015.
 */
public class OTPBean {
    private Date createDate;

    private String userId;

    private String otp;

    public OTPBean(String otp) {
        this.createDate = new Date();
        this.otp = otp;
    }

    public OTPBean(String otp, String userId) {
        this.createDate = new Date();
        this.otp = otp;
        this.userId = userId;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getOtp() {
        return otp;
    }

    public void setOtp(String otp) {
        this.otp = otp;
    }

    public boolean isValid() {
        return false;
    }
}

SecureBankingApp/src/main/webapp/WEB-INF/views/emp/account-list.jsp
<%@ page language="java" contentType="text/html" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bank of Upper Concourse</title>

    <!-- include css -->
    <jsp:include page="../css.jsp"></jsp:include>

    <!-- include js -->
    <jsp:include page="../js.jsp"></jsp:include>
</head>
<body>
<jsp:include page="nav.jsp"></jsp:include>

<div class="container col-sm-8 col-sm-offset-2 ">

    <c:if test="${fn:length(accounts) gt 0}">
        <h3>Account information - <span class="text-muted"><c:out value="${accounts[0].user.name}"/>
            </span></h3>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>#</th>
                <th>Type</th>
                <th>Balance</th>
                <th>Opening date</th>
            </tr>
            </thead>
            <tbody>
            <c:forEach items="${accounts}" var="account" varStatus="loop">
                <tr>
                    <td><c:out value="${account.accountNum}"/></td>
                    <td><c:out value="${accountTypes[account.accountType]}"/></td>
                    <td><fmt:formatNumber value="${account.balance}"
                                          type="currency"/></td>
                    <td><fmt:formatDate value="${account.openingDate}" pattern="dd MMMM yyyy"/></td>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </c:if>
    <c:if test="${fn:length(accounts) eq 0}">
        <div class="well">No accounts found for this user</div>
    </c:if>

</div>

</body>

</html>

SecureBankingApp/src/main/webapp/WEB-INF/views/emp/home.jsp
<%@ page language="java" contentType="text/html" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form" %>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bank of Upper Concourse</title>

    <!-- include css -->
    <jsp:include page="../css.jsp"></jsp:include>

    <!-- include js -->
    <jsp:include page="../js.jsp"></jsp:include>
</head>
<body>
<jsp:include page="nav.jsp"></jsp:include>

<div class="container col-sm-6 col-sm-offset-3 ">

    <c:if test="${page.valid == false}">
        <div class="alert alert-danger">Something wrong</div>
    </c:if>

    <div class="well">
        Welcome - <c:out value="${loggedInUser.name}"/>
    </div>
</div>
</body>

</html>

SecureBankingApp/src/main/webapp/WEB-INF/views/emp/message.jsp
<%@ page language="java" contentType="text/html" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form" %>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bank of Upper Concourse</title>

    <!-- include css -->
    <jsp:include page="../css.jsp"></jsp:include>

    <!-- include js -->
    <jsp:include page="../js.jsp"></jsp:include>
</head>
<body>
<jsp:include page="nav.jsp"></jsp:include>

<div class="container col-sm-6 col-sm-offset-3 ">

    <c:if test="${page.valid == true}">
        <c:if test="${not empty page.message}">
            <div class="alert alert-success">
                <c:out value="${page.message}"></c:out>
            </div>
        </c:if>
    </c:if>
    <c:if test="${page.valid == false}">
        <c:if test="${not empty page.message}">
            <div class="alert alert-danger">
                <c:out value="${page.message}"></c:out>
            </div>
        </c:if>
    </c:if>
</div>
</body>

</html>

SecureBankingApp/src/main/webapp/WEB-INF/views/emp/nav.jsp
<%@ page language="java" contentType="text/html" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form" %>

<nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse"
                    data-target="#navbar"
                    aria-expanded="false"
                    aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<c:url value='/'></c:url>">Bank of Upper Concourse</a>
        </div>
        <p class="navbar-text">
            <small class="text-muted">Hi,</small>
            <span class="text-info"><c:out value="${sessionScope['loggedInUser'].name}"/></span></p>

        <div class="collapse navbar-collapse">
            <jsp:include page="../logout_inc.jsp"/>

            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="<c:url value='/emp/transactions/list' />">Pending Transactions</a></li>
                <li class="active"><a href="<c:url value='/emp/user/list' />">Authorized Users</a></li>
                <li class="active"><a href="<c:url value='/all/update' />">Update Info</a></li>
                <li class="active"><a href="<c:url value='/all/pwd' />">Change Password</a></li>
            </ul>
        </div>
    </div>
    <!--/.container-fluid -->
</nav>

SecureBankingApp/src/main/webapp/WEB-INF/views/emp/transaction-approval-error.jsp
<%@ page language="java" contentType="text/html" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form" %>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bank of Upper Concourse</title>

    <!-- include css -->
    <jsp:include page="../css.jsp"></jsp:include>

    <!-- include js -->
    <jsp:include page="../js.jsp"></jsp:include>
</head>
<body>
<jsp:include page="nav.jsp"/>

<div class="container col-sm-6 col-sm-offset-3 ">
    <p style="color:red"><%= session.getAttribute("approval.err") %>
    </p>
</div>
</body>

</html>

SecureBankingApp/src/main/webapp/WEB-INF/views/emp/transaction-list.jsp
<%@ page language="java" contentType="text/html" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bank of Upper Concourse</title>

    <!-- include css -->
    <jsp:include page="../css.jsp"></jsp:include>

    <!-- include js -->
    <jsp:include page="../js.jsp"></jsp:include>
</head>
<body>
<jsp:include page="nav.jsp"></jsp:include>

<div class="container col-sm-8 col-sm-offset-2 ">

    <h3>Pending non-critical transactions</h3>

    <c:if test="${fn:length(transactions) gt 0}">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Transaction Type</th>
                <th>From Account</th>
                <th>To Account</th>
                <th>Requested Amount</th>
                <th>Available Balance</th>
                <th>Approve</th>
                <th>Deny</th>
            </tr>
            </thead>
            <tbody>
            <c:forEach items="${transactions}" var="transaction" varStatus="loop">
                <tr>
                    <td><c:out value="${transaction.transactionType}"/></td>
                    <td><c:out value="${transaction.fromAccount.accountNum}"/></td>
                    <td><c:out value="${transaction.toAccount.accountNum}"/></td>
                    <td><fmt:formatNumber value="${transaction.amount}"
                                          type="currency"/></td>
                    <td><fmt:formatNumber value="${transaction.fromAccount.balance}"
                                          type="currency"/></td>
                    <td><a href="<c:url value='/emp/transactions/approve/${transaction.transactionId}'/>"
                           class="btn btn-default btn-sm">Approve</a></td>
                    <td><a href="<c:url value='/emp/transactions/deny/${transaction.transactionId}'/>"
                           class="btn btn-default btn-sm">Deny</a></td>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </c:if>
    <c:if test="${fn:length(transactions) eq 0}">
        <div class="well">No pending transactions</div>
    </c:if>

</div>

</body>

</html>

SecureBankingApp/src/main/webapp/WEB-INF/views/emp/user-add.jsp
<%@ page language="java" contentType="text/html" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form" %>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bank of Upper Concourse</title>

    <!-- include css -->
    <jsp:include page="../css.jsp"></jsp:include>

    <!-- include js -->
    <jsp:include page="../js.jsp"></jsp:include>
</head>
<body>
<jsp:include page="nav.jsp"></jsp:include>

<div class="container col-sm-6 col-sm-offset-3 ">


    <div class="well">
        <c:url var="formAction" value="/manage/user/add"/>
        <form:form method="post"
                   class="form-horizontal" commandName="user" action="${formAction}">
            <legend>Add User</legend>
            <form:errors path="*" cssClass="alert alert-danger" element="div"></form:errors>
            <div class="form-group">
                <label class="col-sm-4 control-label" for="userId">Username</label>

                <div class="col-sm-7">
                    <form:input path="userId" class="form-control" type="text"/>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-4 control-label" for="userType">Type</label>

                <div class="col-sm-7">
                    <form:select class="form-control" path="userType" items="${roles}"></form:select>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-4 control-label" for="name">Full name</label>

                <div class="col-sm-7">
                    <form:input path="name" class="form-control" type="text"/>
                </div>
            </div>

            <div class="form-group" id="dobCont">
                <label class="col-sm-4 control-label" for="dateString">Date of birth (YYYY-MM-DD)</label>

                <div class="col-sm-7">
                    <form:input path="dateString" class="form-control" type="text"/>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-4 control-label" for="email">Email</label>

                <div class="col-sm-7">
                    <form:input path="email" class="form-control" type="text"/>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-4 control-label" for="address">Address</label>

                <div class="col-sm-7">
                    <form:input path="address" class="form-control" type="text"/>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-4 control-label" for="phoneNumber">Phone</label>

                <div class="col-sm-7">
                    <form:input path="phoneNumber" class="form-control" type="text"/>
                </div>
            </div>

            <div class="form-group" id="ssnCont">
                <label class="col-sm-4 control-label" for="ssn">SSN</label>

                <div class="col-sm-7">
                    <form:input path="ssn" class="form-control" type="text"/>
                </div>
            </div>

            <div class="form-group" id="genderCont">
                <label class="col-sm-4 control-label" for="gender">Gender</label>

                <div class="col-sm-7">
                    <form:select class="form-control" path="gender" items="${genders}"></form:select>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4"></div>
                <div class="col-sm-7">
                    <input type="submit" id="submit" class="btn btn-primary btn-lg btn-sm-10"
                           value="Add User">
                </div>
            </div>

        </form:form>

    </div>
</div>

<script type="application/javascript">
    (function () {
        $gender = $("#genderCont");
        $ssn = $("#ssnCont");
        $userType = $('#userType');
        $dob = $('#dobCont');
        $userType.change(function () {
            update();
        });

        function update() {
            var val = $userType.val();
            if (val === 'ROLE_MERCHANT') {
                $ssn.hide();
                $gender.hide();
                $dob.hide();
            } else {
                $ssn.show();
                $gender.show();
                $dob.show();
            }
        }

        update();
    })();
</script>
</body>

</html>

SecureBankingApp/src/main/webapp/WEB-INF/views/emp/user-list.jsp
<%@ page language="java" contentType="text/html" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form" %>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bank of Upper Concourse</title>

    <!-- include css -->
    <jsp:include page="../css.jsp"></jsp:include>

    <!-- include js -->
    <jsp:include page="../js.jsp"></jsp:include>
</head>
<body>
<jsp:include page="nav.jsp"></jsp:include>

<div class="container col-sm-8 col-sm-offset-2 ">

    <h3>Users</h3>

    <c:if test="${fn:length(users) gt 0}">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Type</th>
                <th>Email</th>
                <th>Status</th>
                <th>Account</th>
            </tr>
            </thead>
            <tbody>
            <c:forEach items="${users}" var="user" varStatus="loop">
                <tr>
                    <td><c:out value="${loop.index + 1}"/></td>
                    <td><c:out value="${user.name}"/></td>
                    <td><c:out value="${roles[user.userType]}"/></td>
                    <td><c:out value="${user.email}"/></td>
                    <td><c:out value="${status[user.status]}"/></td>
                    <td><a href="<c:url value='/emp/account/${user.userId}'/>"
                           class="btn btn-default btn-sm">Account</a></td>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </c:if>
    <c:if test="${fn:length(users) eq 0}">
        <div class="well">No users found</div>
    </c:if>

</div>

</body>

</html>